version: "3.3"
services:
  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - /var/lib/docker/volumes/redis_volume:/data
